# Generated by Django 3.2.3 on 2021-06-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.IntegerField()),
                ('time_increment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='_archive_profile_friends_+', to='archive.Profile')),
                ('invitations', models.ManyToManyField(related_name='invitations_received', to='archive.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white')], default='white', max_length=6)),
                ('game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessgame')),
                ('player', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_nr', models.IntegerField()),
                ('white_move', models.CharField(max_length=9)),
                ('black_move', models.CharField(max_length=9)),
                ('game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessgame')),
            ],
        ),
        migrations.AddField(
            model_name='chessgame',
            name='game_time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.gametime'),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
