# Generated by Django 3.2.3 on 2021-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
