# Generated by Django 3.2.2 on 2021-05-10 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0002_auto_20210510_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('game_date', models.DateField()),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ChessPlayers',
            new_name='ChessPlayer',
        ),
        migrations.RenameModel(
            old_name='Movements',
            new_name='Movement',
        ),
        migrations.RenameModel(
            old_name='PlayerDetails',
            new_name='PlayerDetail',
        ),
        migrations.DeleteModel(
            name='ChessGames',
        ),
    ]
