# Generated by Django 3.2.2 on 2021-05-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20210510_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='game_time_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.gametime'),
        ),
        migrations.AddField(
            model_name='movement',
            name='game_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessgame'),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='game_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessgame'),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.chessplayer'),
        ),
    ]
