# Generated by Django 3.2.2 on 2021-05-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20210510_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='game_time_id',
            new_name='game_time',
        ),
    ]
