# Generated by Django 3.2.2 on 2021-05-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_rename_game_time_id_chessgame_game_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdetail',
            old_name='player_id',
            new_name='player',
        ),
    ]
