# Generated by Django 3.2.2 on 2021-05-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_rename_player_id_playerdetail_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='user_id',
            new_name='user',
        ),
    ]
