# Generated by Django 3.2.3 on 2021-06-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('archive', '0010_auto_20210521_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('friends', models.ManyToManyField(related_name='_archive_profile_friends_+', to='archive.Profile')),
                ('invitations', models.ManyToManyField(to='archive.Profile')),
            ],
        ),
    ]
